version: "3"
services:
  webapp:
    build:
      context: packages/webapp
    image: trader-webapp:latest
    ports:
      - 80:3000
  api:
    build:
      context: packages/api
    image: trader-api:latest
    ports:
      - "5000:5000"
volumes:
  mongo-data:
